<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3iaiwrb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3iaiwrb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3iaiwrb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3iaiwrb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3iaiwrb\App_KernelDevDebugContainer([
    'container.build_hash' => '3iaiwrb',
    'container.build_id' => '2bd9cd1b',
    'container.build_time' => 1643118128,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3iaiwrb');
