<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container62WZkod\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container62WZkod/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container62WZkod.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container62WZkod\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container62WZkod\App_KernelDevDebugContainer([
    'container.build_hash' => '62WZkod',
    'container.build_id' => 'f25d3ba8',
    'container.build_time' => 1642876512,
], __DIR__.\DIRECTORY_SEPARATOR.'Container62WZkod');
